export const board = [
  {
    id: 0,
    name: 'Start',
    image: 'Start',
    price: 600,
    orientation: 'horizontal',
    type: 'Start',
    priceColor: 'red',
    position: 'top',
    figure: 'square',
  },
  {
    id: 1,
    name: 'Chanel',
    image: 'Chanel',
    price: 600,
    orientation: 'vertical',
    type: 'element',
    priceColor: 'red',
    position: 'top',
    figure: 'vertical',
  },
  {
    id: 2,
    name: 'riddle',
    image: 'riddle',
    price: 0,
    orientation: 'vertical',
    type: 'riddle',
    priceColor: 'red',
    position: 'top',
    figure: 'vertical',
  },
  {
    id: 3,
    name: 'Boss',
    image: 'Boss',
    price: 600,
    orientation: 'vertical',
    type: 'element',
    priceColor: 'red',
    position: 'top',
    figure: 'vertical',
  },
  {
    id: 4,
    name: 'Nalog',
    image: 'Nalog',
    price: 2000,
    orientation: 'vertical',
    type: 'Nalog',
    priceColor: 'red',
    position: 'top',
    figure: 'vertical',
  },
  {
    id: 5,
    name: 'Mercedes',
    image: 'Mercedes',
    price: 2000,
    orientation: 'vertical',
    type: 'element',
    priceColor: 'red',
    position: 'top',
    figure: 'vertical',
  },
  {
    id: 6,
    name: 'Adidas',
    image: 'Adidas',
    price: 1000,
    orientation: 'vertical',
    type: 'element',
    priceColor: 'red',
    position: 'top',
    figure: 'vertical',
  },
  {
    id: 7,
    name: 'riddle',
    image: 'riddle',
    price: 0,
    orientation: 'vertical',
    type: 'riddle',
    priceColor: 'red',
    position: 'top',
    figure: 'vertical',
  },
  {
    id: 8,
    name: 'Puma',
    image: 'Puma',
    price: 1000,
    orientation: 'vertical',
    type: 'element',
    priceColor: 'red',
    position: 'top',
    figure: 'vertical',
  },
  {
    id: 9,
    name: 'Lacoste',
    image: 'Lacoste',
    price: 1200,
    orientation: 'vertical',
    type: 'element',
    priceColor: 'red',
    position: 'top',
    figure: 'vertical',
  },
  {
    id: 10,
    name: 'Jail',
    image: 'Jail',
    price: 0,
    orientation: 'horizontal',
    type: 'Jail',
    priceColor: 'red',
    position: 'top',
    figure: 'square',
  },
];
